### ISSUE TITLE
这个版本反应很慢

### ISSUE THREAD

**Issue by woodnaonly** [eolinker/eoLinker-API-Management-System-OS-2.X#1]
是不是我部署错误了？

**Comment by eolinker** [comment]
应该是不会的，因为几乎不涉及任何的耗时操作，可能和环境有关。
的确不同的环境会导致不同的响应速度。

你可以报一下你的环境配置，比如apache/nginx + php版本（是否用了集成开发环境）等

**Comment by woodnaonly** [comment]
解决了，是我的数据库版本太低了
